### ISSUE TITLE
Heatmode should support solar pref and solar only, not just heat/off

### ISSUE THREAD

**Issue by gjbadros** [bwoodworth/hassio-addons#2]
The node module supports:

heatMode - integer indicating the desired heater mode. Valid values are: 0: "Off", 1: "Solar", 2 : "Solar Preferred", 3 : "Heat Pump", 4: "Don't Change"

But only #3 seems to be reflected in the MQTT messages.  It should both support setting and reading of the mode.  This is important to control whether gas or solar is used when controlling the pool's heating function.

**Comment by bwoodworth** [comment]
Thanks for the issue.  Are you able to test if I add the additional heat modes?

**Comment by gjbadros** [comment]
Actually, I see now that the underlying JS library has been improved to support mutations, so I updated my code that was using the same library.  I have an all-Javascript solution that I tested last night and works great for me.  Good luck and thanks for making me aware of the improvement to the library.

**Comment by bwoodworth** [comment]
Unfortunately the climate entity doesn't allow for custom heat modes.  It does have custom preset modes, but the MQTT climate entity doesn't have those.  I will either have to add presets to the MQTT climate entity or convert this addon to an integration.

**Comment by gjbadros** [comment]
That's not true, you can just list them under "modes" in the yaml config.

"""
  - platform: mqtt
    name: "Pentair Pool"
    min_temp: 40
    max_temp: 104
    modes:
      - "off"
      - "solar"
      - "solar_pref"
      - "heat"
    current_temperature_topic: pentair/pooltemp/state
    action_topic: pentair/circuit/505/state
    mode_command_topic: pentair/heater/pool/mode/set
    mode_state_topic: pentair/heater/pool/mode/state
    temperature_command_topic: pentair/heater/pool/temperature/set
    temperature_state_topic: pentair/heater/pool/setpoint/state
"""

**Comment by bwoodworth** [comment]
I have tried that.  You will get the following error in the logs:

> 2020-04-27 10:06:01 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139920643912976] value is not allowed for dictionary value @ data['hvac_mode']

The MQTT HVAC documentation actually states you can't have custom modes:

> modes
>     (list)(Optional)
> 
>     A list of supported modes. Needs to be a subset of the default values.
> 
>     Default value:
>     [“auto”, “off”, “cool”, “heat”, “dry”, “fan_only”]

preset modes would work, but those are not implemented for MQTT HVAC yet.

**Comment by gjbadros** [comment]
It works fine for me -- I think you're just formatting the YAML wrong or
using the wrong key -- it's called "modes" not "hvac_mode".

**Comment by bwoodworth** [comment]
What version are you on?  Can you show a screenshot of the climate device?

**Comment by bwoodworth** [comment]
Here is my config:

```
climate:
  - platform: mqtt
    unique_id: pool
    name: "Pool"
    min_temp: 40
    max_temp: 104
    modes:
      - "off"
      - "heat"
      - "solar"
      - "solar_pref"
    current_temperature_topic: pentair/pooltemp/state
    action_topic: pentair/circuit/505/state
    mode_command_topic: pentair/heater/pool/mode/set
    mode_state_topic: pentair/heater/pool/mode/state
    temperature_command_topic: pentair/heater/pool/temperature/set
    temperature_state_topic: pentair/heater/pool/setpoint/state
```
